spring:
  mvc:
   view:
    prefix: /WEB-INF/
    suffix: .jsp

s3:
  endpointUrl: http://127.0.0.1:9000
  accessKey: D8NRB2PM6ZUJNOMQL7XQ
  secretKey: 8qXi/laDWz+E+Ntwq9pymF1t0M0AHGbIRcy+/viP
  bucketName: moviefun

albums:
  url: http://localhost:8081/albums
movies:
  url: http://localhost:8082/movies